apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html-deployment
  labels:
    app: app-html
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html
        image: denilsonbonatti/web-app:1.0
        ports:
        - containerPort: 80
